### ISSUE TITLE
Installation of transformr without rtools

### ISSUE THREAD

**Issue by rdatasculptor** [thomasp85/transformr#4]
Due to adminstration and network issues I am not able to install and use rtools, unfortenately... So I was wondering, is there a way to install the transformr package without having to use rtools? Or do do I just have to wait until the package is on cran (or until I have no network restrictions anymore)?

Thanks in advance!

**Comment by thomasp85** [comment]
You can get windows binaries from the appveyor CI service (https://ci.appveyor.com/project/thomasp85/transformr/build/artifacts)

**Comment by rdatasculptor** [comment]
Thanks!!!

Op ma 19 nov. 2018 14:09 schreef Thomas Lin Pedersen <
notifications@github.com:
